### ISSUE TITLE
Test-require Test::More needs 0.96, but should be 0.94

### ISSUE THREAD

**Issue by ppisar** [rjbs/Sub-Exporter-GlobExporter#2]
0.004 release states in META.json:

```
     "test" : {
         "requires" : {
            "File::Spec" : "0",
            "IO::Handle" : "0",
            "IPC::Open3" : "0",
            "Test::More" : "0.96",
            "lib" : "0"
         }
     }
```

But the highest Test::More version specified in the code is 0.94 at t/00-compile.t:6.

I recommend to decrease the value in the metadata.

**Comment by rjbs** [comment]
All of my code requires Test::More 0.96, to allow me to use subtests without plans and for various bugfixes.
